<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestSystem.Core\TestSystem.Core.csproj" />
    <ProjectReference Include="..\TestSystem.Infrastructure\TestSystem.Infrastructure.csproj" />
    <ProjectReference Include="..\TestSystem.Steps\TestSystem.Steps.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="kiến_trúc_c#_cho_chương_trình_test_với_tính_linh_hoạt_cao.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>